const {themes: prismThemes} = require('prism-react-renderer');

const siteUrl = process.env.DOCS_SITE_URL || 'https://rtl-buddy.github.io';
const rootBaseUrl = normalizeBaseUrl(
  process.env.DOCS_ROOT_BASE_URL || '/rtl_buddy/',
);
const baseUrl = normalizeBaseUrl(process.env.DOCS_BASE_URL || '/');
const docsVersion = process.env.DOCS_VERSION || 'dev';
const docsPath = process.env.DOCS_PATH || 'docs';
const autogeneratedSidebar = process.env.DOCS_AUTOGENERATED_SIDEBAR === 'true';
const editRef = process.env.DOCS_EDIT_REF || 'main';
const publishedVersions = parseVersions(
  process.env.DOCS_VERSIONS || docsVersion,
);

function normalizeBaseUrl(value) {
  return `/${value.split('/').filter(Boolean).join('/')}/`;
}

function parseVersions(value) {
  const versions = value
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean);
  return [...new Set(versions)].sort((left, right) => {
    if (left === 'dev') return -1;
    if (right === 'dev') return 1;
    return Number(right.slice(1)) - Number(left.slice(1));
  });
}

function versionItems() {
  return publishedVersions.map((version) => ({
    label: version,
    href: `${siteUrl}${rootBaseUrl}${version}/`,
  }));
}

function publishedUrl(path) {
  return `${siteUrl}${baseUrl}${path}`;
}

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'RTL Buddy',
  tagline: 'RTL design and verification workflows for humans and AI agents',
  favicon: 'img/favicon.svg',
  url: siteUrl,
  baseUrl,
  organizationName: 'rtl-buddy',
  projectName: 'rtl_buddy',
  trailingSlash: true,
  onBrokenLinks: 'throw',
  markdown: {
    format: 'detect',
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
  },
  staticDirectories: ['static', '.docusaurus-agent-static'],

  presets: [
    [
      'classic',
      {
        docs: {
          path: docsPath,
          routeBasePath: '/',
          sidebarPath: autogeneratedSidebar
            ? require.resolve('./sidebars.historical.js')
            : require.resolve('./sidebars.js'),
          editUrl:
            `https://github.com/rtl-buddy/rtl_buddy/edit/${editRef}/docs/`,
          showLastUpdateAuthor: !autogeneratedSidebar,
          showLastUpdateTime: !autogeneratedSidebar,
        },
        blog: false,
        pages: false,
        sitemap: {
          changefreq: 'weekly',
          priority: 0.5,
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      },
    ],
  ],

  themeConfig: {
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'RTL Buddy',
      logo: {
        alt: 'RTL Buddy logo',
        src: 'img/logo.svg',
      },
      items: [
        {
          type: 'dropdown',
          label: docsVersion,
          position: 'left',
          items: versionItems(),
        },
        {
          href: publishedUrl('agent/catalog.json'),
          label: 'Agent docs',
          position: 'right',
        },
        {
          href: 'https://github.com/rtl-buddy/rtl_buddy',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Documentation',
          items: [
            {label: 'Quick Start', to: '/quickstart/'},
            {label: 'CLI Reference', to: '/reference/cli/'},
            {label: 'Agent access', to: '/agents/#local-docs-access'},
          ],
        },
        {
          title: 'Project',
          items: [
            {
              label: 'GitHub',
              href: 'https://github.com/rtl-buddy/rtl_buddy',
            },
            {
              label: 'PyPI',
              href: 'https://pypi.org/project/rtl-buddy/',
            },
          ],
        },
        {
          title: 'For agents',
          items: [
            {label: 'llms.txt', href: publishedUrl('llms.txt')},
            {label: 'Catalog JSON', href: publishedUrl('agent/catalog.json')},
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} RTL Buddy contributors.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['bash', 'python', 'json', 'yaml', 'verilog'],
    },
  },
};

module.exports = config;
