# rtl-buddy
#
# Copyright 2024 rtl_buddy contributors
#
"""Design tokens and brand assets shared by every hub app.

:data:`THEME_CSS` is ``theme.css``, served same-origin at :data:`THEME_CSS_ROUTE`. Its light and dark palettes are authored by hand; the ``:root[data-theme=...]`` blocks after :data:`GENERATED_MARKER` are generated by :func:`build_theme_css`. ``python -m rtl_buddy.hub.theme`` rewrites them, and ``tests/test_hub_theme.py`` fails when the checked-in file differs. :func:`asset_bytes` serves the vendored brand marks under ``assets/``.
"""

from __future__ import annotations

import re
from pathlib import Path


#: Route serving the token sheet.
THEME_CSS_ROUTE = "/hub/theme.css"

#: Prefix for the vendored brand marks (``/hub/assets/<name>``).
ASSETS_ROUTE_PREFIX = "/hub/assets/"

#: Vendored brand mark file names under ``assets/``.
FAVICON_16 = "rtl-buddy-favicon-16.png"
FAVICON_32 = "rtl-buddy-favicon-32.png"
LOGO_80 = "rtl-buddy-logo-80.png"
MASCOT_240 = "rtl-buddy-mascot-240.png"

_ASSETS_DIR = Path(__file__).parent / "assets"
_THEME_CSS_PATH = Path(__file__).parent / "theme.css"

#: Everything from this line to EOF in ``theme.css`` is generated.
GENERATED_MARKER = (
    "/* ==== generated below this line — "
    "`python -m rtl_buddy.hub.theme` rewrites it ==== */"
)

_ROOT_BLOCK_RE = re.compile(r"^:root \{\n(?P<body>.*?)^\}", re.S | re.M)
_DARK_BLOCK_RE = re.compile(
    r"^@media \(prefers-color-scheme: dark\) \{\n(?P<body>.*?)^\}", re.S | re.M
)
_DECL_RE = re.compile(r"^\s*(?P<name>--[a-z0-9-]+):\s*(?P<value>[^;]+);", re.M)


def _declarations(css: str) -> list[tuple[str, str]]:
    """Return ``(--token, value)`` pairs in source order for one CSS block body."""

    return [(m.group("name"), m.group("value").strip()) for m in _DECL_RE.finditer(css)]


def parse_palettes(source: str) -> tuple[list[tuple[str, str]], list[tuple[str, str]]]:
    """Return ``(light, dark)`` declaration lists from the authored part of the sheet.

    ``light`` is the whole ``:root`` block; ``dark`` is only the tokens the media query overrides.
    """

    root = _ROOT_BLOCK_RE.search(source)
    if root is None:
        raise ValueError("theme.css: no top-level `:root {` block")
    dark_media = _DARK_BLOCK_RE.search(source)
    if dark_media is None:
        raise ValueError("theme.css: no `@media (prefers-color-scheme: dark)` block")
    return _declarations(root.group("body")), _declarations(dark_media.group("body"))


def _block(selector: str, scheme: str, decls: list[tuple[str, str]]) -> str:
    lines = [f"{selector} {{", f"  color-scheme: {scheme};"]
    width = max((len(name) for name, _ in decls), default=0) + 1
    lines += [f"  {(name + ':'):<{width + 1}} {value};" for name, value in decls]
    lines.append("}")
    return "\n".join(lines)


def build_theme_css(source: str) -> str:
    """Return the authored sheet followed by the generated theme-pin blocks.

    ``source`` may be the authored part alone or a previously generated file; everything from :data:`GENERATED_MARKER` on is discarded, so the function is idempotent. Only tokens the dark media query overrides are re-stated in the two pin blocks.
    """

    authored = source.split(GENERATED_MARKER)[0].rstrip("\n")
    light, dark = parse_palettes(authored)
    light_by_name = dict(light)
    overridden = [name for name, _ in dark]
    missing = [name for name in overridden if name not in light_by_name]
    if missing:
        raise ValueError(
            "theme.css: dark block overrides tokens absent from :root: "
            + ", ".join(missing)
        )
    light_overrides = [(name, light_by_name[name]) for name in overridden]
    return "\n".join(
        [
            authored,
            "",
            GENERATED_MARKER,
            "/* An app that pins its theme (a ?theme= param, a toggle, a host",
            " * page) sets data-theme on <html>; these two blocks make that",
            " * attribute win in BOTH directions — a light pin has to beat the",
            " * dark media query, a dark pin has to beat the :root defaults.",
            " * Generated from the two blocks above so the palette exists once. */",
            "",
            _block(':root[data-theme="light"]', "light", light_overrides),
            "",
            _block(':root[data-theme="dark"]', "dark", dark),
            "",
        ]
    )


def read_theme_source() -> str:
    """Return the checked-in ``theme.css`` text."""

    return _THEME_CSS_PATH.read_text(encoding="utf-8")


def in_source_checkout() -> bool:
    """Return whether ``theme.css`` is inside a git working tree (not an installed wheel)."""

    return any(
        (parent / ".git").exists() for parent in _THEME_CSS_PATH.resolve().parents
    )


def write_theme_css() -> Path:
    """Regenerate ``theme.css`` in place and return its path."""

    _THEME_CSS_PATH.write_text(build_theme_css(read_theme_source()), encoding="utf-8")
    return _THEME_CSS_PATH


THEME_CSS: str = read_theme_source()
"""The sheet, read once at import."""


def theme_css_bytes() -> bytes:
    """Return the body for ``GET /hub/theme.css``."""

    return THEME_CSS.encode("utf-8")


def asset_names() -> list[str]:
    """Return the sorted names of the vendored brand marks."""

    return sorted(p.name for p in _ASSETS_DIR.glob("*.png"))


def asset_bytes(name: str) -> bytes | None:
    """Return the body for ``GET /hub/assets/<name>``, or ``None`` if there is no such mark.

    ``name`` is client-supplied, so it is matched against the directory listing instead of joined onto a path.
    """

    if name not in asset_names():
        return None
    return (_ASSETS_DIR / name).read_bytes()


def favicon_link_tags(prefix: str = ASSETS_ROUTE_PREFIX) -> str:
    """Return the ``<link rel="icon">`` pair for a hub page."""

    return (
        f'<link rel="icon" type="image/png" sizes="32x32" href="{prefix}{FAVICON_32}">\n'
        f'  <link rel="icon" type="image/png" sizes="16x16" href="{prefix}{FAVICON_16}">'
    )


def main() -> None:  # pragma: no cover - developer entry point
    if not in_source_checkout():
        raise SystemExit(
            "theme.css is not inside a git working tree — refusing to rewrite an "
            "installed copy. Run this from a source checkout."
        )
    path = write_theme_css()
    print(f"regenerated {path}")


if __name__ == "__main__":  # pragma: no cover
    main()


__all__ = [
    "ASSETS_ROUTE_PREFIX",
    "FAVICON_16",
    "FAVICON_32",
    "GENERATED_MARKER",
    "LOGO_80",
    "MASCOT_240",
    "THEME_CSS",
    "THEME_CSS_ROUTE",
    "asset_bytes",
    "asset_names",
    "build_theme_css",
    "favicon_link_tags",
    "in_source_checkout",
    "parse_palettes",
    "read_theme_source",
    "theme_css_bytes",
    "write_theme_css",
]
