"""Tests for stripping parameter overrides from `blocks:` instances (rtl_buddy#712).

Yosys writes every parameter of an instance of a parameterised `(* blackbox *)` stub as a
`#(...)` override, and OpenROAD's `read_verilog` rejects it with STA-0171. The overrides are
checked against the block's synthesis and removed before any OpenROAD session reads the
netlist.
"""

from pathlib import Path
from textwrap import dedent

import pytest

from rtl_buddy.tools import block_params, pnr_abstract
from rtl_buddy.tools.block_params import (
    BlockInstance,
    BlockParamError,
    check_instances,
    clean_netlist,
    defined_modules,
    parse_value,
    strip_overrides,
    values_equal,
)
from rtl_buddy.tools.synth_yosys import clean_block_netlist, yosys_read_lib_paths

from test_pnr_blocks import _BLOCK_YAML, _block_suite, _ref, _top_backend, _write

# The parent netlist Yosys writes for the issue's reproducer, with the block's module
# renamed to the test suites' `blk_top`.
_ISSUE_NETLIST = dedent("""\
    /* Generated by Yosys 0.64 */

    (* top =  1  *)
    (* src = "top.sv:1.8" *)
    module top(clk, d, q);
      input clk;
      wire clk;
      input [15:0] d;
      wire [15:0] d;
      output [15:0] q;
      wire [15:0] q;
      (* src = "top.sv:2.3" *)
      blk_top #(
        .AW(32'd5),
        .W(32'd16)
      ) \\u_blk  (
        .clk(clk),
        .d(d),
        .q(q)
      );
    endmodule
    """)


def test_the_issue_netlist_loses_its_overrides_and_keeps_its_connections():
    cleaned, [inst] = strip_overrides(_ISSUE_NETLIST, {"blk_top"})

    assert "#(" not in cleaned
    assert "  blk_top \\u_blk  (\n    .clk(clk)," in cleaned
    assert inst.module == "blk_top"
    assert inst.instance == "u_blk"
    assert inst.params == {"AW": "32'd5", "W": "32'd16"}
    assert inst.line == 13
    # Nothing but the override list changed.
    removed = "#(\n    .AW(32'd5),\n    .W(32'd16)\n  ) "
    assert cleaned == _ISSUE_NETLIST.replace(f"blk_top {removed}", "blk_top ")


def test_only_instances_of_the_named_modules_are_rewritten():
    text = dedent("""\
        module top(a);
          // blk_top #(.W(1)) commented (
          (* note = "blk_top #(.W(2)) u_attr (" *)
          other #(.W(32'd3)) u_other (.a(a));
          blk_top #(.W(32'd16), .NAME("a)b,c")) u_one (.a(a));
          \\blk_top #( .W ( 32'd16 ) ) \\u_two[0] (.a(a));
        endmodule
        module blk_top #(parameter W = 8) (a);
        endmodule
        """)

    cleaned, found = strip_overrides(text, {"blk_top"})

    assert [(i.instance, i.params) for i in found] == [
        ("u_one", {"W": "32'd16", "NAME": '"a)b,c"'}),
        ("u_two[0]", {"W": "32'd16"}),
    ]
    assert "other #(.W(32'd3)) u_other" in cleaned
    assert "// blk_top #(.W(1)) commented (" in cleaned
    assert '(* note = "blk_top #(.W(2)) u_attr (" *)' in cleaned
    assert "blk_top u_one (.a(a));" in cleaned
    assert "\\blk_top \\u_two[0] (.a(a));" in cleaned
    # A module header with a parameter port list is not an instance.
    assert "module blk_top #(parameter W = 8) (a);" in cleaned


def test_an_instance_written_without_a_space_keeps_its_names_apart():
    cleaned, [inst] = strip_overrides("blk_top #(.W(1))u_x (.a(a));", {"blk_top"})
    assert cleaned == "blk_top u_x (.a(a));"
    assert inst.instance == "u_x"


def test_positional_overrides_are_kept_by_position():
    _, [inst] = strip_overrides("blk_top #(16, (2+1)) u (.a(a));", {"blk_top"})
    assert inst.params == {"#0": "16", "#1": "(2+1)"}


def test_a_netlist_without_block_overrides_is_returned_unchanged():
    text = "module top; blk_top u (.a(a)); endmodule\n"
    assert strip_overrides(text, {"blk_top"}) == (text, [])


@pytest.mark.parametrize(
    "literal,configured,equal",
    [
        ("32'd16", 16, True),
        ("32'd16", 8, False),
        ("32'sd16", 16, True),
        ("-32'sd5", -5, True),
        ("32'd4294967291", -5, True),
        ("8'hff", "8'hFF", True),
        ("8'b1111_1111", 255, True),
        ("16", 16, True),
        ("1'b1", True, True),
        ("1'b0", True, False),
        ('"fast"', "fast", True),
        ('"fast"', "slow", False),
        ("1.5", 1.5, True),
        ("4'bx01z", "4'bX01Z", True),
        ("4'bx01z", 1, False),
    ],
)
def test_overrides_compare_by_value(literal, configured, equal):
    assert values_equal(literal, configured) is equal


def test_literals_parse_to_value_and_width():
    assert parse_value("32'd5") == (5, 32)
    assert parse_value("32'sd4294967295") == (-1, 32)
    assert parse_value("'h1f") == (31, None)
    assert parse_value('"x"') == "x"
    assert parse_value("$clog2(W)") is None


def _inst(name, **params):
    return BlockInstance(module="blk_top", instance=name, line=1, params=params)


def test_an_override_that_differs_from_the_block_synthesis_is_refused():
    expected = {"blk_top": ("synth run 's'", {"W": 16})}
    check_instances([_inst("u_blk", W="32'd16", AW="32'd5")], expected, "n.v")

    with pytest.raises(BlockParamError) as info:
        check_instances([_inst("u_blk", W="32'd8", AW="32'd3")], expected, "n.v")
    message = str(info.value)
    assert "instance 'u_blk' (line 1) of block 'blk_top' sets W=32'd8" in message
    assert "synthesised with W=16 (synth run 's')" in message


def test_parameters_the_block_synthesis_does_not_set_are_not_checked():
    # AW is a localparam derived from W; the hardened netlist records no value for it.
    expected = {"blk_top": ("synth run 's'", {"W": 16})}
    check_instances([_inst("u_blk", W="32'd16", AW="32'd99")], expected, "n.v")


def test_instances_of_one_block_with_different_parameters_are_refused():
    with pytest.raises(BlockParamError, match=r"different parameters \(W\)"):
        check_instances([_inst("u_a", W="32'd8"), _inst("u_b", W="32'd16")], {}, "n.v")


def test_defined_modules_ignores_comments_and_strings():
    text = dedent("""\
        // module fake_a;
        /* module fake_b; */
        initial $display("module fake_c");
        (* blackbox *)
        module blk_top #(parameter W = 8) (input a);
        endmodule
        macromodule \\esc$name (b); endmodule
        """)
    assert defined_modules(text) == {"blk_top", "esc$name"}


def _block_with_params(tmp_path, params="{W: 16}"):
    """A resolved block whose synthesis sets `params:`."""
    suite = _block_suite(tmp_path)
    _write(
        tmp_path / "blk/models.yaml",
        'rtl-buddy-filetype: model_config\nmodels:\n  - name: "blk_top"\n'
        "    filelist: []\n",
    )
    _write(
        tmp_path / "blk/synth.yaml",
        "rtl-buddy-filetype: synth_config\nsyntheses:\n  - name: s\n"
        "    desc: s\n    model: blk_top\n    model_path: models.yaml\n"
        f"    tool: yosys\n    params: {params}\n",
    )
    return pnr_abstract.resolve_block(_ref(suite))


def test_clean_netlist_writes_a_checked_copy(tmp_path):
    block = _block_with_params(tmp_path)
    source = _write(tmp_path / "synth_netlist.v", _ISSUE_NETLIST)
    dest = str(tmp_path / "pnr_netlist.v")

    path, [inst] = clean_netlist(str(source), dest, [block])

    assert path == dest
    assert "#(" not in Path(dest).read_text()
    assert source.read_text() == _ISSUE_NETLIST
    assert inst.instance == "u_blk"


def test_clean_netlist_without_overrides_reads_the_source_and_drops_a_stale_copy(
    tmp_path,
):
    block = _block_with_params(tmp_path)
    source = _write(tmp_path / "synth_netlist.v", "module top; endmodule\n")
    stale = _write(tmp_path / "pnr_netlist.v", "old\n")

    assert clean_netlist(str(source), str(stale), [block]) == (str(source), [])
    assert not stale.exists()


def test_a_mismatched_netlist_is_refused_naming_the_netlist(tmp_path):
    block = _block_with_params(tmp_path, params="{W: 8}")
    source = _write(tmp_path / "synth_netlist.v", _ISSUE_NETLIST)

    with pytest.raises(BlockParamError, match=f"^{source}: instance 'u_blk'"):
        clean_netlist(str(source), str(tmp_path / "out.v"), [block])
    assert not (tmp_path / "out.v").exists()


def test_synthesis_strips_its_netlist_in_place_and_keeps_a_clean_one(tmp_path):
    block = _block_with_params(tmp_path)
    netlist = _write(tmp_path / "synth_netlist.v", _ISSUE_NETLIST)

    assert clean_block_netlist(str(netlist), [block], "top_synth") is None
    assert "#(" not in netlist.read_text()
    # A second pass finds nothing to strip and must leave the netlist in place.
    assert clean_block_netlist(str(netlist), [block], "top_synth") is None
    assert netlist.exists() and "blk_top \\u_blk" in netlist.read_text()


def test_synthesis_refuses_a_mismatched_override(tmp_path):
    block = _block_with_params(tmp_path, params="{W: 8}")
    netlist = _write(tmp_path / "synth_netlist.v", _ISSUE_NETLIST)

    error = clean_block_netlist(str(netlist), [block], "top_synth")

    assert "sets W=32'd16" in error and "W=8" in error


def test_yosys_skips_the_abstract_liberty_of_a_block_the_sources_stub(tmp_path):
    block = _block_with_params(tmp_path)
    stub = _write(
        tmp_path / "blk_bb.sv",
        "(* blackbox *)\nmodule blk_top #(parameter int W = 8) (input logic a);\n"
        "endmodule\n",
    )
    other = _write(tmp_path / "top.sv", "module top; endmodule\n")
    libs = ["cells.lib", block.lib]

    assert yosys_read_lib_paths(libs, [block], [str(stub), str(other)], "s") == [
        "cells.lib"
    ]
    # Without a stub the abstract is the blackbox, so it stays.
    assert yosys_read_lib_paths(libs, [block], [str(other)], "s") == libs
    assert yosys_read_lib_paths(libs, [], [str(stub)], "s") == libs


def _top_netlist(tmp_path, text):
    return _write(tmp_path / "top/artefacts/s/synth_netlist.v", text)


def test_a_top_run_reads_a_stripped_copy_of_the_netlist(tmp_path, monkeypatch):
    _block_with_params(tmp_path)
    backend, launched = _top_backend(tmp_path, monkeypatch, _BLOCK_YAML)
    source = _top_netlist(tmp_path, _ISSUE_NETLIST)

    res = backend.run()

    assert res.is_pass(), res.results
    copy = Path(backend.artefact_dir) / "pnr_netlist.v"
    script = Path(backend._script_path()).read_text()
    assert f"set NETLIST         {copy}\n" in script
    assert "#(" not in copy.read_text()
    assert source.read_text() == _ISSUE_NETLIST
    assert len(launched) == 1


def test_a_top_run_with_a_clean_netlist_reads_it_directly(tmp_path, monkeypatch):
    _block_with_params(tmp_path)
    backend, _ = _top_backend(tmp_path, monkeypatch, _BLOCK_YAML)
    source = _top_netlist(
        tmp_path, "module top; blk_top u_blk (.clk(clk)); endmodule\n"
    )

    assert backend.run().is_pass()

    assert f"set NETLIST         {source}\n" in Path(backend._script_path()).read_text()
    assert not (Path(backend.artefact_dir) / "pnr_netlist.v").exists()


def test_a_top_run_with_a_mismatched_override_fails_before_openroad(
    tmp_path, monkeypatch
):
    _block_with_params(tmp_path, params="{W: 8}")
    backend, launched = _top_backend(tmp_path, monkeypatch, _BLOCK_YAML)
    _top_netlist(tmp_path, _ISSUE_NETLIST)

    res = backend.run()

    assert res.results["fail_stage"] == "setup"
    assert (
        "instance 'u_blk' (line 13) of block 'blk_top' sets W=32'd16"
        in res.results["desc"]
    )
    assert res.results["blocks"][0]["name"] == "blk_top"
    assert launched == []


def test_power_reads_a_stripped_snapshot(tmp_path):
    from test_power import _make_power_backend

    block = _block_with_params(tmp_path)
    backend = _make_power_backend(tmp_path)
    (tmp_path / "synth_netlist.v").write_text(_ISSUE_NETLIST)
    backend._write_script()
    backend._blocks = [block]

    assert backend._snapshot_netlist() is None

    snapshot = Path(backend._netlist_snapshot_path()).read_text()
    assert "#(" not in snapshot and "blk_top \\u_blk" in snapshot


def test_power_refuses_a_mismatched_override(tmp_path):
    from test_power import _make_power_backend

    block = _block_with_params(tmp_path, params="{W: 8}")
    backend = _make_power_backend(tmp_path)
    netlist = tmp_path / "synth_netlist.v"
    netlist.write_text(_ISSUE_NETLIST)
    backend._write_script()
    backend._blocks = [block]

    error = backend._snapshot_netlist()

    assert error.startswith(f"{netlist}: instance 'u_blk'")
    assert not Path(backend._netlist_snapshot_path()).exists()


def test_block_expectations_tolerate_an_unloadable_synthesis(tmp_path):
    block = pnr_abstract.resolve_block(_ref(_block_suite(tmp_path)))
    assert block_params.block_expectations([block]) == {
        "blk_top": ("synthesis not loadable", {})
    }


_PARAM_STUB = (
    "(* blackbox *)\n"
    "module blk_top #(parameter int W = 8, localparam int AW = $clog2(W)) (\n"
    "  input logic clk, input logic [W-1:0] d, output logic [W-1:0] q);\n"
    "endmodule\n"
    "module glue (input wire a, output wire z);\n"
    "  assign z = ~a;\n"
    "endmodule\n"
)


def test_blackbox_modules_spans_a_parameterised_header():
    [bb] = block_params.blackbox_modules(_PARAM_STUB)
    assert bb.name == "blk_top"
    assert _PARAM_STUB[bb.header_start : bb.header_end].endswith(
        "output logic [W-1:0] q);"
    )
    assert _PARAM_STUB[bb.start : bb.end].endswith("endmodule")


def test_the_openroad_backend_drops_a_parameterised_stub_with_a_master(tmp_path):
    """Stage 2 reads the block's LEF and Liberty; a stub copy of the SV header would fail STA-0171."""
    from test_synth import _make_openroad, _make_synth_cfg, _write_filelist

    src = _write(tmp_path / "blk_bb.sv", _PARAM_STUB)
    or_synth = _make_openroad(
        tmp_path, synth_cfg=_make_synth_cfg(name="test_synth", model_name="top")
    )
    _write_filelist(or_synth, src)

    [stub] = or_synth._write_or_blackbox_stubs({"blk_top"})

    text = Path(stub).read_text()
    assert "blk_top" not in text
    assert "module glue" in text
    # Without a master the header is kept as a port-only stub.
    [stub] = or_synth._write_or_blackbox_stubs(set())
    text = Path(stub).read_text()
    assert (
        "module blk_top #(parameter int W = 8, localparam int AW = $clog2(W))" in text
    )
    assert text.count("endmodule") == 2


def test_the_synth_runner_hands_the_backend_its_resolved_blocks(tmp_path, monkeypatch):
    from unittest.mock import MagicMock

    from rtl_buddy.tools import synth_yosys
    from test_pnr_blocks import _synth_runner

    _block_suite(tmp_path)
    seen = {}

    def _fake_run(self):
        seen["blocks"] = [b.ref.name for b in self.blocks]
        return MagicMock(results={"result": "PASS", "desc": None})

    monkeypatch.setattr(synth_yosys.YosysSynth, "run", _fake_run)
    runner = _synth_runner(
        tmp_path,
        "    blocks:\n      - {name: blk_top, pnr: blk_pnr, pnr-path: ../blk/pnr.yaml}\n",
    )

    runner.run()

    assert seen == {"blocks": ["blk_top"]}
