"""Tests for stripping parameter overrides from `blocks:` instances (rtl_buddy#712).

Yosys writes every parameter of an instance of a parameterised `(* blackbox *)` stub as a
`#(...)` override, and OpenROAD's `read_verilog` rejects it with STA-0171. The overrides are
checked against the block's synthesis and removed before any OpenROAD session reads the
netlist.
"""

import json
import os
import shutil
import subprocess
from pathlib import Path
from textwrap import dedent

import pytest

from rtl_buddy.tools import block_params, pnr_abstract
from rtl_buddy.tools.block_params import (
    BlockParamError,
    StripSelfCheckError,
    block_instances,
    check_params,
    check_ports,
    clean_netlist,
    literals_equal,
    parse_value,
    strip_overrides,
    values_equal,
)
from rtl_buddy.tools.synth_yosys import (
    clean_block_netlist,
    probe_block_parameters,
    yosys_read_lib_paths,
)

from test_pnr_blocks import _BLOCK_YAML, _block_suite, _ref, _top_backend, _write

# The parent netlist Yosys writes for the issue's reproducer, with the block's module
# renamed to the test suites' `blk_top`.
_ISSUE_NETLIST = dedent("""\
    /* Generated by Yosys 0.64 */

    (* top =  1  *)
    (* src = "top.sv:1.8" *)
    module top(clk, d, q);
      input clk;
      wire clk;
      input [15:0] d;
      wire [15:0] d;
      output [15:0] q;
      wire [15:0] q;
      (* src = "top.sv:2.3" *)
      blk_top #(
        .AW(32'd4),
        .W(32'd16)
      ) \\u_blk  (
        .clk(clk),
        .d(d),
        .q(q)
      );
    endmodule
    """)


def test_the_issue_netlist_loses_its_overrides_and_keeps_its_connections():
    cleaned, [inst] = strip_overrides(_ISSUE_NETLIST, {"blk_top"})

    assert "#(" not in cleaned
    assert "  blk_top \\u_blk  (\n    .clk(clk)," in cleaned
    assert inst.module == "blk_top"
    assert inst.instance == "u_blk"
    assert inst.params == {"AW": "32'd4", "W": "32'd16"}
    assert inst.line == 13
    # Nothing but the override list changed.
    removed = "#(\n    .AW(32'd4),\n    .W(32'd16)\n  ) "
    assert cleaned == _ISSUE_NETLIST.replace(f"blk_top {removed}", "blk_top ")


def test_only_instances_of_the_named_modules_are_rewritten():
    text = dedent("""\
        module top(a);
          // blk_top #(.W(1)) commented (
          (* note = "blk_top #(.W(2)) u_attr (" *)
          other #(.W(32'd3)) u_other (.a(a));
          blk_top #(.W(32'd16), .NAME("a)b,c")) u_one (.a(a));
          \\blk_top #( .W ( 32'd16 ) ) \\u_two[0] (.a(a));
        endmodule
        module blk_top #(parameter W = 8) (a);
        endmodule
        """)

    cleaned, found = strip_overrides(text, {"blk_top"})

    assert [(i.instance, i.params) for i in found] == [
        ("u_one", {"W": "32'd16", "NAME": '"a)b,c"'}),
        ("u_two[0]", {"W": "32'd16"}),
    ]
    assert "other #(.W(32'd3)) u_other" in cleaned
    assert "// blk_top #(.W(1)) commented (" in cleaned
    assert '(* note = "blk_top #(.W(2)) u_attr (" *)' in cleaned
    assert "blk_top u_one (.a(a));" in cleaned
    assert "\\blk_top \\u_two[0] (.a(a));" in cleaned
    # A module header with a parameter port list is not an instance.
    assert "module blk_top #(parameter W = 8) (a);" in cleaned


def test_an_instance_written_without_a_space_keeps_its_names_apart():
    cleaned, [inst] = strip_overrides("blk_top #(.W(1))u_x (.a(a));", {"blk_top"})
    assert cleaned == "blk_top u_x (.a(a));"
    assert inst.instance == "u_x"


def test_positional_overrides_are_kept_by_position():
    _, [inst] = strip_overrides("blk_top #(16, (2+1)) u (.a(a));", {"blk_top"})
    assert inst.params == {"#0": "16", "#1": "(2+1)"}


def test_a_netlist_without_block_overrides_is_returned_unchanged():
    text = "module top; blk_top u (.a(a)); endmodule\n"
    assert strip_overrides(text, {"blk_top"}) == (text, [])


@pytest.mark.parametrize(
    "literal,configured,equal",
    [
        ("32'd16", 16, True),
        ("32'd16", 8, False),
        ("32'sd16", 16, True),
        ("-32'sd5", -5, True),
        ("32'd4294967291", -5, True),
        ("8'hff", "8'hFF", True),
        ("8'b1111_1111", 255, True),
        ("16", 16, True),
        ("1'b1", True, True),
        ("1'b0", True, False),
        ('"fast"', "fast", True),
        ('"fast"', "slow", False),
        ("1.5", 1.5, True),
        ("4'bx01z", "4'bX01Z", True),
        ("4'bx01z", 1, False),
        ('"a_b c"', "a_b c", True),
        ('"ab c"', "a_b c", False),
        ('"a_bc"', "a_b c", False),
        ('"a_b c"', "abc", False),
        ("32'd1_0", "1_0", True),
    ],
)
def test_overrides_compare_by_value(literal, configured, equal):
    assert values_equal(literal, configured) is equal


def test_literals_parse_to_value_and_width():
    assert parse_value("32'd5") == (5, 32)
    assert parse_value("32'sd4294967295") == (-1, 32)
    assert parse_value("'h1f") == (31, None)
    assert parse_value('"x"') == "x"
    assert parse_value("$clog2(W)") is None


def test_blackbox_modules_ignores_comments_and_strings_and_reads_lifetimes():
    text = dedent("""\
        // (* blackbox *) module fake_a; endmodule
        initial $display("(* blackbox *) module fake_c;");
        (* blackbox *)
        module automatic blk_top #(parameter W = 8) (input a);
        endmodule
        (* blackbox *)
        module static plain (input b);
        endmodule
        module real_one (input c); endmodule
        """)
    found = block_params.blackbox_modules(text)
    assert [(bb.name, bb.parameterised) for bb in found] == [
        ("blk_top", True),
        ("plain", False),
    ]


def _blk_lef(width=16, extra=""):
    """The abstract LEF of `blk_top`, as `write_abstract_lef` writes it for a `width`-bit block."""

    def pin(name, direction, use="SIGNAL"):
        return (
            f"  PIN {name}\n    DIRECTION {direction} ;\n    USE {use} ;\n"
            "    PORT\n      LAYER met2 ;\n        RECT 0 0 1 1 ;\n    END\n"
            f"  END {name}\n"
        )

    pins = pin("clk", "INPUT")
    pins += "".join(pin(f"d[{i}]", "INPUT") for i in range(width))
    pins += "".join(pin(f"q[{i}]", "OUTPUT") for i in range(width))
    pins += pin("VDD", "INOUT", "POWER") + pin("VSS", "INOUT", "GROUND") + extra
    return (
        "VERSION 5.8 ;\nMACRO blk_top\n  CLASS BLOCK ;\n  SIZE 50 BY 50 ;\n"
        f"{pins}END blk_top\nEND LIBRARY\n"
    )


def _record(parameters, *, complete=True, order=("W",), frontend="slang"):
    return block_params.ParamRecord(
        module="blk_top",
        frontend=frontend,
        complete=complete,
        parameters=dict(parameters),
        order=list(order),
    )


_W16 = {
    "AW": "32'b00000000000000000000000000000100",
    "W": "32'b00000000000000000000000000010000",
}
_W8 = {
    "AW": "32'b00000000000000000000000000000011",
    "W": "32'b00000000000000000000000000001000",
}


def _block_with_params(tmp_path, params="{W: 16}", *, width=16, record=_W16, **kw):
    """A resolved block whose synthesis sets `params:`, with a `width`-bit abstract and, unless `record` is None, a parameter record."""
    suite = _block_suite(tmp_path, lef_text=_blk_lef(width))
    if record is not None:
        out = tmp_path / "blk/artefacts/blk_pnr/abstract"
        _write(out / "blk_top.params.json", _record(record, **kw).to_json())
    _write(
        tmp_path / "blk/models.yaml",
        'rtl-buddy-filetype: model_config\nmodels:\n  - name: "blk_top"\n'
        "    filelist: []\n",
    )
    _write(
        tmp_path / "blk/synth.yaml",
        "rtl-buddy-filetype: synth_config\nsyntheses:\n  - name: s\n"
        "    desc: s\n    model: blk_top\n    model_path: models.yaml\n"
        f"    tool: yosys\n    params: {params}\n",
    )
    return pnr_abstract.resolve_block(_ref(suite))


def test_clean_netlist_writes_a_checked_copy(tmp_path):
    block = _block_with_params(tmp_path)
    source = _write(tmp_path / "synth_netlist.v", _ISSUE_NETLIST)
    dest = str(tmp_path / "pnr_netlist.v")

    path, [inst] = clean_netlist(str(source), dest, [block])

    assert path == dest
    assert "#(" not in Path(dest).read_text()
    assert source.read_text() == _ISSUE_NETLIST
    assert inst.instance == "u_blk"


def test_clean_netlist_without_overrides_reads_the_source_and_drops_a_stale_copy(
    tmp_path,
):
    block = _block_with_params(tmp_path)
    source = _write(tmp_path / "synth_netlist.v", "module top; endmodule\n")
    stale = _write(tmp_path / "pnr_netlist.v", "old\n")

    assert clean_netlist(str(source), str(stale), [block]) == (str(source), [])
    assert not stale.exists()


def test_a_mismatched_netlist_is_refused_naming_the_netlist(tmp_path):
    block = _block_with_params(tmp_path, params="{W: 8}", width=8, record=_W8)
    source = _write(tmp_path / "synth_netlist.v", _ISSUE_NETLIST)

    with pytest.raises(BlockParamError, match=f"^{source}: instance 'u_blk'"):
        clean_netlist(str(source), str(tmp_path / "out.v"), [block])
    assert not (tmp_path / "out.v").exists()


def test_synthesis_strips_its_netlist_in_place_and_keeps_a_clean_one(tmp_path):
    block = _block_with_params(tmp_path)
    netlist = _write(tmp_path / "synth_netlist.v", _ISSUE_NETLIST)

    assert clean_block_netlist(str(netlist), [block], "top_synth") is None
    assert "#(" not in netlist.read_text()
    # A second pass finds nothing to strip and must leave the netlist in place.
    assert clean_block_netlist(str(netlist), [block], "top_synth") is None
    assert netlist.exists() and "blk_top \\u_blk" in netlist.read_text()


def test_synthesis_refuses_a_mismatched_override(tmp_path):
    block = _block_with_params(tmp_path, params="{W: 8}", width=8, record=_W8)
    netlist = _write(tmp_path / "synth_netlist.v", _ISSUE_NETLIST)

    error = clean_block_netlist(str(netlist), [block], "top_synth")

    assert "sets AW=32'd4, W=32'd16" in error
    assert "hardened with AW=32'd3, W=32'd8" in error


def test_yosys_skips_the_abstract_liberty_of_a_block_the_sources_stub(tmp_path):
    block = _block_with_params(tmp_path)
    stub = _write(
        tmp_path / "blk_bb.sv",
        "(* blackbox *)\nmodule blk_top #(parameter int W = 8) (input logic a);\n"
        "endmodule\n",
    )
    other = _write(tmp_path / "top.sv", "module top; endmodule\n")
    libs = ["cells.lib", block.lib]

    assert yosys_read_lib_paths(libs, [block], [str(stub), str(other)], "s") == [
        "cells.lib"
    ]
    # Without a stub the abstract is the blackbox, so it stays.
    assert yosys_read_lib_paths(libs, [block], [str(other)], "s") == libs
    assert yosys_read_lib_paths(libs, [], [str(stub)], "s") == libs


def test_yosys_keeps_the_abstract_for_a_model_or_a_stub_without_parameters(tmp_path):
    """Only a parameterised blackbox stub replaces the abstract; a simulation model of the
    module under `ifndef SYNTHESIS would leave Yosys with no definition at all.
    """
    block = _block_with_params(tmp_path)
    model = _write(
        tmp_path / "blk_model.sv",
        "`ifndef SYNTHESIS\nmodule blk_top #(parameter int W = 8) (input logic a);\n"
        "endmodule\n`endif\n",
    )
    plain_stub = _write(
        tmp_path / "blk_bb.sv",
        "(* blackbox *)\nmodule blk_top (input logic a);\nendmodule\n",
    )
    automatic_stub = _write(
        tmp_path / "blk_auto_bb.sv",
        "(* blackbox *)\nmodule automatic blk_top #(parameter W = 8) (input a);\n"
        "endmodule\n",
    )
    libs = ["cells.lib", block.lib]

    assert yosys_read_lib_paths(libs, [block], [str(model)], "s") == libs
    assert yosys_read_lib_paths(libs, [block], [str(plain_stub)], "s") == libs
    assert yosys_read_lib_paths(libs, [block], [str(automatic_stub)], "s") == [
        "cells.lib"
    ]


def _top_netlist(tmp_path, text):
    return _write(tmp_path / "top/artefacts/s/synth_netlist.v", text)


def test_a_top_run_reads_a_stripped_copy_of_the_netlist(tmp_path, monkeypatch):
    _block_with_params(tmp_path)
    backend, launched = _top_backend(tmp_path, monkeypatch, _BLOCK_YAML)
    source = _top_netlist(tmp_path, _ISSUE_NETLIST)

    res = backend.run()

    assert res.is_pass(), res.results
    copy = Path(backend.artefact_dir) / "pnr_netlist.v"
    script = Path(backend._script_path()).read_text()
    assert f"set NETLIST         {copy}\n" in script
    assert "#(" not in copy.read_text()
    assert source.read_text() == _ISSUE_NETLIST
    assert len(launched) == 1
    inputs = backend._checkpoint_inputs(
        backend.root_cfg.get_pnr_platform_cfg(), backend._script_path()
    )
    assert inputs["netlist"]["path"] == str(copy)
    assert inputs["synth_netlist"]["path"] == str(source)


def test_a_top_run_with_a_clean_netlist_reads_it_directly(tmp_path, monkeypatch):
    _block_with_params(tmp_path)
    backend, _ = _top_backend(tmp_path, monkeypatch, _BLOCK_YAML)
    source = _top_netlist(
        tmp_path,
        _ISSUE_NETLIST.replace(
            "blk_top #(\n    .AW(32'd4),\n    .W(32'd16)\n  ) ", "blk_top "
        ),
    )

    assert backend.run().is_pass()

    assert f"set NETLIST         {source}\n" in Path(backend._script_path()).read_text()
    assert not (Path(backend.artefact_dir) / "pnr_netlist.v").exists()


def test_a_top_run_with_a_mismatched_override_fails_before_openroad(
    tmp_path, monkeypatch
):
    _block_with_params(tmp_path, params="{W: 8}", width=8, record=_W8)
    backend, launched = _top_backend(tmp_path, monkeypatch, _BLOCK_YAML)
    _top_netlist(tmp_path, _ISSUE_NETLIST)

    res = backend.run()

    assert res.results["fail_stage"] == "setup"
    assert (
        "instance 'u_blk' (line 13) of block 'blk_top' sets AW=32'd4, W=32'd16"
        in res.results["desc"]
    )
    assert res.results["blocks"][0]["name"] == "blk_top"
    assert launched == []


def test_power_reads_a_stripped_snapshot(tmp_path):
    from test_power import _make_power_backend

    block = _block_with_params(tmp_path)
    backend = _make_power_backend(tmp_path)
    (tmp_path / "synth_netlist.v").write_text(_ISSUE_NETLIST)
    backend._write_script()
    backend._blocks = [block]

    assert backend._snapshot_netlist() is None

    snapshot = Path(backend._netlist_snapshot_path()).read_text()
    assert "#(" not in snapshot and "blk_top \\u_blk" in snapshot


def test_power_refuses_a_mismatched_override(tmp_path):
    from test_power import _make_power_backend

    block = _block_with_params(tmp_path, params="{W: 8}", width=8, record=_W8)
    backend = _make_power_backend(tmp_path)
    netlist = tmp_path / "synth_netlist.v"
    netlist.write_text(_ISSUE_NETLIST)
    backend._write_script()
    backend._blocks = [block]

    error = backend._snapshot_netlist()

    assert error.startswith(f"{netlist}: instance 'u_blk'")
    assert not Path(backend._netlist_snapshot_path()).exists()


def test_block_expectations_tolerate_an_unloadable_synthesis(tmp_path):
    block = pnr_abstract.resolve_block(_ref(_block_suite(tmp_path)))
    assert block_params.block_expectations([block]) == {
        "blk_top": ("synthesis not loadable", {})
    }


_PARAM_STUB = (
    "(* blackbox *)\n"
    "module blk_top #(parameter int W = 8, localparam int AW = $clog2(W)) (\n"
    "  input logic clk, input logic [W-1:0] d, output logic [W-1:0] q);\n"
    "endmodule\n"
    "module glue (input wire a, output wire z);\n"
    "  assign z = ~a;\n"
    "endmodule\n"
)


def test_blackbox_modules_spans_a_parameterised_header():
    [bb] = block_params.blackbox_modules(_PARAM_STUB)
    assert bb.name == "blk_top"
    assert _PARAM_STUB[bb.header_start : bb.header_end].endswith(
        "output logic [W-1:0] q);"
    )
    assert _PARAM_STUB[bb.start : bb.end].endswith("endmodule")


def test_the_openroad_backend_drops_a_parameterised_stub_with_a_master(tmp_path):
    """Stage 2 reads the block's LEF and Liberty; a stub copy of the SV header would fail STA-0171."""
    from test_synth import _make_openroad, _make_synth_cfg, _write_filelist

    src = _write(tmp_path / "blk_bb.sv", _PARAM_STUB)
    or_synth = _make_openroad(
        tmp_path, synth_cfg=_make_synth_cfg(name="test_synth", model_name="top")
    )
    _write_filelist(or_synth, src)

    [stub] = or_synth._write_or_blackbox_stubs({"blk_top"})

    text = Path(stub).read_text()
    assert "blk_top" not in text
    assert "module glue" in text
    # Without a master the header is kept as a port-only stub.
    [stub] = or_synth._write_or_blackbox_stubs(set())
    text = Path(stub).read_text()
    assert (
        "module blk_top #(parameter int W = 8, localparam int AW = $clog2(W))" in text
    )
    assert text.count("endmodule") == 2


def test_the_synth_runner_hands_the_backend_its_resolved_blocks(tmp_path, monkeypatch):
    from unittest.mock import MagicMock

    from rtl_buddy.tools import synth_yosys
    from test_pnr_blocks import _synth_runner

    _block_suite(tmp_path)
    seen = {}

    def _fake_run(self):
        seen["blocks"] = [b.ref.name for b in self.blocks]
        return MagicMock(results={"result": "PASS", "desc": None})

    monkeypatch.setattr(synth_yosys.YosysSynth, "run", _fake_run)
    runner = _synth_runner(
        tmp_path,
        "    blocks:\n      - {name: blk_top, pnr: blk_pnr, pnr-path: ../blk/pnr.yaml}\n",
    )

    runner.run()

    assert seen == {"blocks": ["blk_top"]}


def test_a_netlist_that_cannot_be_copied_fails_under_its_own_event(
    tmp_path, monkeypatch
):
    from rtl_buddy.tools import pnr_openroad

    _block_with_params(tmp_path)
    backend, launched = _top_backend(tmp_path, monkeypatch, _BLOCK_YAML)
    _top_netlist(tmp_path, _ISSUE_NETLIST)
    events = []
    real_log_event = pnr_openroad.log_event

    def _record(logger, level, event, **fields):
        events.append(event)
        real_log_event(logger, level, event, **fields)

    def _no_space(*_a, **_k):
        raise OSError(28, "No space left on device")

    monkeypatch.setattr(pnr_openroad, "log_event", _record)
    monkeypatch.setattr(block_params, "clean_netlist", _no_space)

    res = backend.run()

    assert res.results["fail_stage"] == "setup"
    assert res.results["desc"].startswith("could not strip block parameter overrides")
    assert launched == []
    assert "pnr.block_netlist_failed" in events
    assert "pnr.block_params_mismatch" not in events


def test_a_stripped_copy_leaves_no_staging_file(tmp_path):
    block = _block_with_params(tmp_path)
    source = _write(tmp_path / "synth_netlist.v", _ISSUE_NETLIST)

    clean_netlist(str(source), str(tmp_path / "pnr_netlist.v"), [block])

    assert sorted(p.name for p in tmp_path.iterdir() if p.is_file()) == [
        "pnr_netlist.v",
        "synth_netlist.v",
    ]


# --- Ports against the abstract ------------------------------------------------------------


def _netlist(instance: str, decls: str = "") -> str:
    return (
        "module top(clk, d, q);\n  input clk;\n  wire clk;\n  input [15:0] d;\n"
        "  wire [15:0] d;\n  output [15:0] q;\n  wire [15:0] q;\n"
        f"{decls}  {instance}\nendmodule\n"
    )


def _check_ports(tmp_path, instance, *, width=16, decls=""):
    block = _block_with_params(tmp_path, width=width)
    insts = block_instances(_netlist(instance, decls), {"blk_top"}, "n.v")
    return check_ports(insts, [block], "n.v")


def test_a_block_hardened_at_its_default_width_refuses_a_wider_parent(tmp_path):
    """The block was hardened with W at its default 8; the parent sets W=16 and the
    synthesis had no params:, so only the abstract's pin widths can tell.
    """
    with pytest.raises(BlockParamError) as info:
        _check_ports(
            tmp_path,
            "blk_top #(.W(32'd16)) u_blk (.clk(clk), .d(d), .q(q));",
            width=8,
        )
    assert (
        "instance 'u_blk' (line 8) of block 'blk_top': port 'd' is connected to 16 "
        "bit(s), but the hardened block's pin is 8 bit(s) wide"
    ) in str(info.value)


def test_connection_widths_come_from_selects_concatenations_and_constants(tmp_path):
    assert (
        _check_ports(
            tmp_path,
            "blk_top u_blk (.clk(clk), .d({ d[7:0], 4'h0, \\x.y [3:0] }), "
            ".q({ 2 { q[7:0] } }));",
            decls="  wire [3:0] \\x.y ;\n",
        )
        == []
    )


@pytest.mark.parametrize(
    "connection,reason",
    [
        (".d(16)", "unsized constant 16"),
        (".d(nope)", "undeclared net nope"),
        (".d(d[i])", "i"),
        (".d(d[3 +: 4])", "+"),
    ],
)
def test_a_connection_rb_cannot_size_fails_closed(tmp_path, connection, reason):
    with pytest.raises(BlockParamError) as info:
        _check_ports(tmp_path, f"blk_top u_blk (.clk(clk), {connection}, .q(q));")
    assert "cannot tell the width of port 'd'" in str(info.value)
    assert reason in str(info.value)


def test_a_port_the_abstract_lacks_is_refused(tmp_path):
    with pytest.raises(BlockParamError, match="port 'en' is not a pin"):
        _check_ports(tmp_path, "blk_top u_blk (.clk(clk), .d(d), .q(q), .en(clk));")


def test_an_unconnected_input_fails_and_an_unconnected_output_warns(tmp_path):
    with pytest.raises(BlockParamError, match="input pin 'd' is not connected"):
        _check_ports(tmp_path, "blk_top u_blk (.clk(clk), .d(), .q(q));")
    warnings = _check_ports(tmp_path / "w", "blk_top u_blk (.clk(clk), .d(d));")
    assert warnings == [
        "n.v: output pin 'q' of block 'blk_top' is not connected on instance "
        "'u_blk' (line 8)"
    ]


def test_positional_port_connections_and_instance_arrays_fail_closed(tmp_path):
    with pytest.raises(BlockParamError, match="positional port connections"):
        _check_ports(tmp_path, "blk_top u_blk (clk, d, q);")
    with pytest.raises(BlockParamError, match="instance arrays"):
        _check_ports(tmp_path / "a", "blk_top u_blk [1:0] (.clk(clk));")


def test_supply_pins_need_no_connection(tmp_path):
    lef = abstract_pins_of(tmp_path)
    assert {n for n, p in lef.items() if p.supply} == {"VDD", "VSS"}
    assert (lef["d"].width, lef["d"].direction) == (16, "INPUT")


def abstract_pins_of(tmp_path):
    block = _block_with_params(tmp_path)
    return block_params.abstract_pins(block.lef, "blk_top")


# --- Parameters against the elaborated record ----------------------------------------------


def _check_params(tmp_path, instance, **kw):
    block = _block_with_params(tmp_path, **kw)
    insts = block_instances(_netlist(instance), {"blk_top"}, "n.v")
    return check_params(insts, [block], "n.v")


def test_a_block_hardened_at_its_default_refuses_an_override_params_never_named(
    tmp_path,
):
    """params: is empty, so the old check passed; the record knows W was 8."""
    with pytest.raises(BlockParamError) as info:
        _check_params(
            tmp_path,
            "blk_top #(.W(32'd16)) u_blk (.clk(clk), .d(d), .q(q));",
            params="{}",
            record=_W8,
        )
    assert "sets W=32'd16, but the block was hardened with W=32'd8" in str(info.value)


def test_a_localparam_mismatch_is_refused(tmp_path):
    with pytest.raises(BlockParamError) as info:
        _check_params(
            tmp_path,
            "blk_top #(.AW(32'd5), .W(32'd16)) u_blk (.clk(clk), .d(d), .q(q));",
        )
    assert "sets AW=32'd5, but the block was hardened with AW=32'd4" in str(info.value)


def test_positional_overrides_map_to_names_through_the_recorded_order(tmp_path):
    assert (
        _check_params(tmp_path, "blk_top #(16) u_blk (.clk(clk), .d(d), .q(q));") == []
    )
    with pytest.raises(BlockParamError, match="sets W=8, but the block was hardened"):
        _check_params(tmp_path / "b", "blk_top #(8) u_blk (.clk(clk), .d(d), .q(q));")
    with pytest.raises(BlockParamError, match="parameter order is unknown"):
        _check_params(
            tmp_path / "c",
            "blk_top #(16) u_blk (.clk(clk), .d(d), .q(q));",
            order=(),
        )


def test_an_override_the_block_does_not_have_is_refused(tmp_path):
    with pytest.raises(BlockParamError, match="has no parameter 'DEPTH'"):
        _check_params(tmp_path, "blk_top #(.DEPTH(4)) u_blk (.clk(clk), .d(d), .q(q));")


def test_an_incomplete_record_warns_about_what_it_cannot_check(tmp_path):
    warnings = _check_params(
        tmp_path,
        "blk_top #(.AW(32'd4), .W(32'd16)) u_blk (.clk(clk), .d(d), .q(q));",
        record={"W": _W16["W"]},
        complete=False,
        frontend="verilog",
    )
    assert warnings == [
        "n.v: AW on block 'blk_top' is not checked on instance 'u_blk' (line 8): "
        "the block's record (verilog frontend) has no localparams — harden it with "
        "frontend: slang for a complete record"
    ]


def test_without_a_record_params_are_checked_with_a_warning_to_reharden(tmp_path):
    instance = "blk_top #(.W(32'd16)) u_blk (.clk(clk), .d(d), .q(q));"
    warnings = _check_params(tmp_path, instance, record=None)
    assert warnings == [
        "block 'blk_top': its abstract records no elaborated parameters, so only the "
        "synthesis's params: are checked — re-harden the block with this rtl_buddy"
    ]
    with pytest.raises(BlockParamError, match="synthesised with W=8"):
        _check_params(tmp_path / "b", instance, record=None, params="{W: 8}")


def test_instances_of_one_block_with_different_overrides_are_refused(tmp_path):
    block = _block_with_params(tmp_path, record={"W": _W16["W"]}, complete=False)
    netlist = _netlist(
        "blk_top #(.W(32'd16)) u_a (.clk(clk), .d(d), .q(q));\n"
        "  blk_top #(.W(16)) u_b (.clk(clk), .d(d), .q(q));\n"
        '  blk_top #(.W(32\'d16), .MODE("x")) u_c (.clk(clk), .d(d), .q(q));'
    )
    insts = block_instances(netlist, {"blk_top"}, "n.v")
    with pytest.raises(BlockParamError, match=r"different parameters \(MODE\)"):
        check_params(insts, [block], "n.v")


# --- The strip checks itself --------------------------------------------------------------


def test_a_strip_that_changes_anything_else_is_an_internal_error(monkeypatch):
    real = block_params._rewrite

    def _also_renames(text, sites):
        cleaned, changed = real(text, sites)
        return cleaned.replace("clk(clk)", "clk(nope)"), changed

    monkeypatch.setattr(block_params, "_rewrite", _also_renames)
    with pytest.raises(StripSelfCheckError, match="changed more than"):
        strip_overrides(_ISSUE_NETLIST, {"blk_top"})


def test_the_strip_is_verified_on_tricky_input():
    text = (
        'module t; blk_top #(.S("#( ) u"), .W(32\'d1))u_a(.x(y)); '
        "\\blk_top #(1) \\u_b[0] (.x(y)); endmodule\n"
    )
    cleaned, found = strip_overrides(text, {"blk_top"})
    assert [i.instance for i in found] == ["u_a", "u_b[0]"]
    assert strip_overrides(cleaned, {"blk_top"}) == (cleaned, [])


# --- Real Yosys: the structure survives the strip -------------------------------------------

_YOSYS = shutil.which("yosys")


def _yosys_structure(tmp_path, netlist: str, name: str):
    """Read `netlist` with `blk_top` a blackbox and return its cells (types and connections) and nets, without instance parameters."""
    # One path for both reads: Yosys names generated cells after the source file.
    src = tmp_path / "netlist_read.v"
    src.write_text(netlist)
    out = tmp_path / f"{name}.json"
    stub = tmp_path / "blk_bb.v"
    stub.write_text(
        "(* blackbox *) module blk_top #(parameter W = 8) "
        "(input clk, input [W-1:0] d, output [W-1:0] q); endmodule\n"
    )
    subprocess.run(
        [
            _YOSYS,
            "-q",
            "-p",
            f"read_verilog {stub}; read_verilog {src}; proc; write_json {out}",
        ],
        check=True,
        capture_output=True,
    )
    design = json.loads(out.read_text())["modules"]["top"]
    cells = {
        name: {"type": c["type"], "connections": c["connections"]}
        for name, c in design["cells"].items()
    }
    nets = {name: n["bits"] for name, n in design["netnames"].items()}
    return cells, nets, design["ports"]


@pytest.mark.skipif(_YOSYS is None, reason="yosys not installed")
def test_yosys_reads_the_same_structure_before_and_after_the_strip(tmp_path):
    """Synthesise a parent of a parameterised blackbox with Yosys, strip the overrides,
    and read both netlists back: cells, connections, nets and ports must be identical.
    """
    (tmp_path / "top.v").write_text(
        "module top(input clk, input [15:0] a, input [7:0] b, output [15:0] q, "
        "output [7:0] r);\n"
        "  reg [15:0] s; always @(posedge clk) s <= a ^ {b, b};\n"
        "  blk_top #(.W(16)) u_blk (.clk(clk), .d(s), .q(q));\n"
        "  blk_top #(.W(8)) \\u.odd (.clk(clk), .d({b[3:0], 4'h5}), .q(r));\n"
        "endmodule\n"
    )
    (tmp_path / "stub.v").write_text(
        "(* blackbox *) module blk_top #(parameter W = 8) "
        "(input clk, input [W-1:0] d, output [W-1:0] q); endmodule\n"
    )
    original = tmp_path / "netlist.v"
    subprocess.run(
        [
            _YOSYS,
            "-q",
            "-p",
            f"read_verilog {tmp_path / 'stub.v'}; read_verilog {tmp_path / 'top.v'}; "
            f"synth -top top; write_verilog -noattr {original}",
        ],
        check=True,
        capture_output=True,
    )
    text = original.read_text()
    assert "blk_top #(" in text
    stripped, found = strip_overrides(text, {"blk_top"})
    assert len(found) == 2 and "#(" not in stripped

    assert _yosys_structure(tmp_path, text, "before") == _yosys_structure(
        tmp_path, stripped, "after"
    )


# --- Real Yosys: the parameter probe -----------------------------------------------------


def _probe_synth(tmp_path, frontend, params):
    from types import SimpleNamespace

    from rtl_buddy.config.synth import SynthToolOpts

    blk = _write(
        tmp_path / "blk.sv",
        "module blk #(parameter int W = 8, localparam int AW = $clog2(W)) (\n"
        "  input logic clk, input logic [W-1:0] d, output logic [W-1:0] q);\n"
        "  always_ff @(posedge clk) q <= d;\nendmodule\n",
    )
    synth_dir = tmp_path / "synth"
    _write(synth_dir / "synth.f", f"{blk}\n")
    opts = SynthToolOpts()
    opts.frontend = frontend
    if frontend == "slang":
        opts.plugin_path = os.environ["RTL_BUDDY_SLANG_PLUGIN"]
    tool = SimpleNamespace(get_opts=lambda _o: opts, get_executable=lambda: _YOSYS)
    root_cfg = SimpleNamespace(
        get_synth_tool_cfg=lambda _n: tool, get_project_rootdir=lambda: str(tmp_path)
    )
    synth_cfg = SimpleNamespace(
        get_top=lambda: "blk",
        get_params=lambda: params,
        get_defines=lambda: None,
        get_tool_name=lambda: "yosys",
        get_tool_overrides_for=lambda _n: None,
    )
    return probe_block_parameters(
        synth_cfg, root_cfg, str(synth_dir), str(tmp_path / "p")
    )


@pytest.mark.skipif(
    _YOSYS is None or not os.environ.get("RTL_BUDDY_SLANG_PLUGIN"),
    reason="yosys or the yosys-slang plugin (RTL_BUDDY_SLANG_PLUGIN) not available",
)
@pytest.mark.parametrize("params,w,aw", [({"W": 16}, 16, 4), ({}, 8, 3)])
def test_the_slang_probe_records_every_parameter_and_localparam(
    tmp_path, params, w, aw
):
    record = _probe_synth(tmp_path, "slang", params)
    assert record.complete and record.order == ["W"]
    assert parse_value(record.parameters["W"])[0] == w
    assert parse_value(record.parameters["AW"])[0] == aw


@pytest.mark.skipif(_YOSYS is None, reason="yosys not installed")
def test_the_native_probe_records_parameters_and_is_marked_incomplete(tmp_path):
    record = _probe_synth(tmp_path, "verilog", {"W": 16})
    assert not record.complete
    assert set(record.parameters) == {"W"}
    assert parse_value(record.parameters["W"])[0] == 16


def test_an_instance_after_a_procedural_block_is_still_checked(tmp_path):
    netlist = _netlist(
        "always @(posedge clk) begin end\n  blk_top u_blk (.clk(clk), .d(d), .q(q));"
    )
    [inst] = block_instances(netlist, {"blk_top"}, "n.v")
    assert inst.connections == {"clk": 1, "d": 16, "q": 16}


def test_a_net_with_two_packed_dimensions_fails_closed(tmp_path):
    with pytest.raises(BlockParamError, match="declaration rb cannot size"):
        _check_ports(
            tmp_path,
            "blk_top u_blk (.clk(clk), .d(m), .q(q));",
            decls="  wire [1:0][7:0] m;\n",
        )


def test_an_override_on_an_instance_rb_cannot_read_is_refused(tmp_path):
    block = _block_with_params(tmp_path)
    text = "module top; blk_top #(.W(32'd16)) u_blk; endmodule\n"
    with pytest.raises(BlockParamError, match="could not be read as an instance"):
        block_params.clean_text(text, [block], "n.v")


# --- Review of #719: the reviewer's reproducers (rev719/d1..d7, perf) ----------------------


@pytest.mark.parametrize(
    "a,b,equal",
    [
        # d6: a block hardened with BASE='h1000 at its default; the parent's 12'h000
        # matches only the low 12 bits and must not pass.
        ("12'h000", "32'b00000000000000000001000000000000", False),
        ("32'h1000", "32'b00000000000000000001000000000000", True),
        ("'h1000", "32'd4096", True),
        # Same width: the bits decide, since a record carries no signedness.
        ("-32'sd3", "32'b11111111111111111111111111111101", True),
        ("32'd4294967293", "-32'sd3", True),
        # Different widths: whole values, sign-extended only when signed.
        ("8'sb11111101", "32'd4294967293", False),
        ("8'sb11111101", "-3", True),
        ("4'b10x1", "4'b10X1", True),
        ("8'hx", "8'bxxxxxxxx", True),
        ("8'hx0", "8'bxxxx0000", True),
        ("4'bx01z", "4'b0011", False),
        ('"a_b c"', '"a_b c"', True),
    ],
)
def test_literals_compare_as_whole_values(a, b, equal):
    assert literals_equal(a, b) is equal


@pytest.mark.parametrize(
    "literal,configured,equal",
    [
        ("32'd4294967295", -1, True),
        ("12'h000", 4096, False),
        ("12'hfff", -1, True),
        ("12'hfff", 4095, True),
        ("12'hfff", 8191, False),
    ],
)
def test_a_yaml_integer_compares_modulo_the_literals_own_width(
    literal, configured, equal
):
    assert values_equal(literal, configured) is equal


def test_a_hardened_default_is_not_matched_by_its_low_bits(tmp_path):
    """d6, end to end through the parameter check."""
    with pytest.raises(BlockParamError) as info:
        _check_params(
            tmp_path,
            "blk_top #(.BASE(12'h000)) u_blk (.clk(clk), .d(d), .q(q));",
            record={"BASE": "32'b00000000000000000001000000000000"},
            order=("BASE",),
        )
    assert "sets BASE=12'h000, but the block was hardened with BASE=32'd4096" in str(
        info.value
    )


# d3: the native frontend derives a copy of a parameterised blackbox per parameter set.
_PARAMOD_NETLIST = _netlist(
    "\\$paramod\\blk_top\\W=s32'00000000000000000000000000010000  u_blk (\n"
    "    .clk(clk),\n    .d(d),\n    .q(q)\n  );"
)
_HASHED_NETLIST = _netlist(
    "\\$paramod$ccb5f337d60472a9ed5c481e0947040a631ef213\\blk_top  u_blk (\n"
    "    .clk(clk),\n    .d(d),\n    .q(q)\n  );"
)


def test_a_native_frontend_instance_is_checked_and_renamed_to_the_block(tmp_path):
    block = _block_with_params(
        tmp_path, record={"W": _W16["W"]}, complete=False, frontend="verilog"
    )

    cleaned, [inst] = block_params.clean_text(_PARAMOD_NETLIST, [block], "n.v")

    assert inst.params == {"W": "32'sb00000000000000000000000000010000"}
    assert inst.connections == {"clk": 1, "d": 16, "q": 16}
    assert "$paramod" not in cleaned and "  blk_top  u_blk (" in cleaned


def test_a_native_frontend_instance_with_the_wrong_parameters_is_refused(tmp_path):
    block = _block_with_params(
        tmp_path, width=8, record={"W": _W8["W"]}, complete=False, frontend="verilog"
    )
    with pytest.raises(BlockParamError, match="hardened with W=32'd8"):
        block_params.clean_text(_PARAMOD_NETLIST, [block], "n.v")


def test_a_hashed_native_frontend_instance_fails_closed_naming_slang(tmp_path):
    block = _block_with_params(tmp_path)
    with pytest.raises(BlockParamError) as info:
        block_params.clean_text(_HASHED_NETLIST, [block], "n.v")
    assert "named by a hash" in str(info.value)
    assert "frontend: slang" in str(info.value)


def test_unpacked_array_ports_are_sized_from_their_concatenation(tmp_path):
    """d2: Yosys flattens `arr[2]` of 4 bits into a concatenation."""
    lef = _blk_lef(8, extra="")
    block = _block_with_params(tmp_path, width=8, record=_W8)
    Path(block.lef).write_text(lef)
    netlist = (
        "module top(clk, a0, a1, q);\n  input clk;\n  wire clk;\n  input [3:0] a0;\n"
        "  wire [3:0] a0;\n  input [3:0] a1;\n  wire [3:0] a1;\n  wire [7:0] \\u_wrap.x ;\n"
        "  output [7:0] q;\n  wire [7:0] q;\n"
        "  blk_top #(\n    .AW(32'd3),\n    .W(32'd8)\n  ) \\u_wrap.u_blk  (\n"
        "    .clk(clk),\n    .d({ a0, a1 }),\n    .q(q)\n  );\nendmodule\n"
    )
    [inst] = block_instances(netlist, {"blk_top"}, "n.v")
    assert inst.instance == "u_wrap.u_blk"
    assert inst.connections == {"clk": 1, "d": 8, "q": 8}


def test_an_escaped_net_with_brackets_in_its_name_is_sized_from_its_declaration(
    tmp_path,
):
    """d7: a memory word Yosys names `\\mem[1] `."""
    assert (
        _check_ports(
            tmp_path,
            "blk_top u_blk (.clk(clk), .d(\\mem[1] ), .q(q));",
            decls="  wire [15:0] \\mem[1] ;\n",
        )
        == []
    )


def test_a_package_import_before_the_parameter_list_keeps_the_order():
    """d1: `module blk import p::*; #(...)`."""
    text = (
        "module blk import p::*, q::x; #(parameter int W = 8, localparam int AW = "
        "$clog2(W), parameter logic [63:0] K = 64'h1, parameter bit signed [7:0] N = "
        '-3, parameter string S = "ab") (input logic clk);\nendmodule\n'
    )
    assert block_params.parameter_port_names(text, "blk") == ["W", "K", "N", "S"]
    stub = "(* blackbox *)\n" + text
    [bb] = block_params.blackbox_modules(stub)
    assert bb.parameterised


def test_a_module_header_with_a_lifetime_is_not_an_instance(tmp_path):
    block = _block_with_params(tmp_path)
    netlist = _ISSUE_NETLIST + (
        "module automatic blk_top #(parameter W = 8) (clk, d, q);\n"
        "  input clk;\n  input [W-1:0] d;\n  output [W-1:0] q;\nendmodule\n"
    )
    cleaned, [inst] = block_params.clean_text(netlist, [block], "n.v")
    assert inst.instance == "u_blk"
    assert "module automatic blk_top #(parameter W = 8)" in cleaned


def test_a_comment_between_the_master_and_its_override_list_survives(tmp_path):
    block = _block_with_params(tmp_path)
    netlist = _netlist(
        "blk_top /* keep */ #(.W(32'd16)) u_blk (.clk(clk), .d(d), .q(q));"
    )
    cleaned, [inst] = block_params.clean_text(netlist, [block], "n.v")
    assert "blk_top /* keep */  u_blk (.clk(clk)" in cleaned
    assert inst.params == {"W": "32'd16"}


def test_lef_busbitchars_and_escaped_brackets(tmp_path):
    lef = tmp_path / "b.lef"
    lef.write_text(
        'BUSBITCHARS "<>" ;\nMACRO m\n'
        + "".join(
            f"  PIN {n}\n    DIRECTION INPUT ;\n    USE SIGNAL ;\n  END {n}\n"
            for n in ("d<0>", "d<1>", "d<2>", "x\\[0\\]", "y[3]")
        )
        + "END m\n"
    )
    pins = block_params.abstract_pins(str(lef), "m")
    assert (pins["d"].width, pins["x[0]"].width, pins["y[3]"].width) == (3, 1, 1)


def test_yosys_json_strings_keep_a_real_trailing_space():
    assert block_params.yosys_json_literal("0101 ") == '"0101"'
    assert block_params.yosys_json_literal("ab ") == '"ab "'
    assert block_params.yosys_json_literal("0101") == "4'b0101"


def test_the_probe_quotes_string_params_and_keeps_numbers():
    from rtl_buddy.tools.synth_yosys import _probe_value

    assert _probe_value("fast") == '"fast"'
    assert _probe_value('"fast"') == '"fast"'
    assert _probe_value("8'hff") == "8'hff"
    assert _probe_value("4'bx01z") == "4'bx01z"
    assert _probe_value(16) == "16"
    assert _probe_value(True) == "1"
    assert _probe_value('a"b') == '"a\\"b"'


def test_warnings_are_reported_once_per_block_and_key(tmp_path):
    block = _block_with_params(
        tmp_path, record={"W": _W16["W"]}, complete=False, frontend="verilog"
    )
    netlist = _netlist(
        "\n".join(
            f"  blk_top #(.AW(32'd4), .W(32'd16)) u_{i} (.clk(clk), .d(d));"
            for i in range(3)
        )
    )
    insts = block_instances(netlist, {"blk_top"}, "n.v")
    warnings = check_params(insts, [block], "n.v") + check_ports(insts, [block], "n.v")
    assert len(warnings) == 2
    assert all("'u_0' (line 8) and 2 more instance(s)" in w for w in warnings)


def test_a_rewrite_that_touches_the_rest_of_the_netlist_is_an_internal_error(
    monkeypatch,
):
    real = block_params._rewrite

    def _edits_a_declaration(text, sites):
        cleaned, changed = real(text, sites)
        return cleaned.replace("input clk;", "input clk ;", 1), changed

    monkeypatch.setattr(block_params, "_rewrite", _edits_a_declaration)
    with pytest.raises(StripSelfCheckError, match="outside the block instances"):
        strip_overrides(_ISSUE_NETLIST, {"blk_top"})


def _perf_netlist(n_inst: int, cells_per_inst: int = 40) -> str:
    """A flat netlist of inverters with `n_inst` block instances spread through it (rev719/perf)."""
    lines = [
        "module top(clk, d, q);",
        "  input clk;",
        "  wire clk;",
        "  input [15:0] d;",
    ]
    lines += ["  wire [15:0] d;", "  output [15:0] q;", "  wire [15:0] q;"]
    n_cells = n_inst * cells_per_inst
    lines += [f"  wire _{i}_;" for i in range(n_cells)]
    lines += [f"  wire [15:0] \\qq{b} ;" for b in range(n_inst)]
    for i in range(n_cells):
        lines += [
            f'  (* src = "top.sv:{i}.1-{i}.9" *)',
            f"  sky130_fd_sc_hd__inv_1 _c{i}_ (",
            f"    .A(_{i}_),",
            f"    .Y(_{(i + 1) % n_cells}_)",
            "  );",
        ]
        if i % cells_per_inst == 0:
            b = i // cells_per_inst
            lines += [
                "  blk_top #(",
                "    .AW(32'd4),",
                "    .W(32'd16)",
                f"  ) \\u_blk{b}  (",
                "    .clk(clk),",
                "    .d({ d[7:0], d[15:8] }),",
                f"    .q(\\qq{b} )",
                "  );",
            ]
    lines.append("endmodule")
    return "\n".join(lines) + "\n"


def test_checking_and_stripping_scale_linearly(tmp_path):
    """rev719/perf: the first version re-counted lines per instance and tokenised the
    netlist three times, which was quadratic (99 s at 8k instances on 1.16M lines).
    A 4x larger netlist must cost well under 16x.
    """
    import time

    block = _block_with_params(tmp_path)
    timings = []
    for n in (250, 1000):
        text = _perf_netlist(n)
        start = time.perf_counter()
        _, insts = block_params.clean_text(text, [block], "n.v")
        timings.append(time.perf_counter() - start)
        assert len(insts) == n
    small, large = timings
    assert large < 8 * small + 0.5, timings
    assert large < 20, timings


def _probe_sources(tmp_path, frontend, params, sources: dict[str, str], libs=()):
    """Run the parameter probe on `sources` (name -> text) with top `blk`."""
    from types import SimpleNamespace

    from rtl_buddy.config.synth import SynthToolOpts

    paths = [_write(tmp_path / name, text) for name, text in sources.items()]
    synth_dir = tmp_path / "synth"
    _write(synth_dir / "synth.f", "".join(f"{p}\n" for p in paths))
    opts = SynthToolOpts()
    opts.frontend = frontend
    if frontend == "slang":
        opts.plugin_path = os.environ["RTL_BUDDY_SLANG_PLUGIN"]
    tool = SimpleNamespace(get_opts=lambda _o: opts, get_executable=lambda: _YOSYS)
    root_cfg = SimpleNamespace(
        get_synth_tool_cfg=lambda _n: tool, get_project_rootdir=lambda: str(tmp_path)
    )
    synth_cfg = SimpleNamespace(
        get_top=lambda: "blk",
        get_params=lambda: params,
        get_defines=lambda: None,
        get_tool_name=lambda: "yosys",
        get_tool_overrides_for=lambda _n: None,
        get_lib_paths=lambda: [str(p) for p in libs],
        get_platform=lambda: None,
        get_blocks=lambda: [],
    )
    return probe_block_parameters(
        synth_cfg, root_cfg, str(synth_dir), str(tmp_path / "p")
    )


_BLK_WITH_CHILDREN = (
    "module blk #(parameter int W = 8, localparam int AW = $clog2(W)) "
    "(input logic clk, input logic [W-1:0] d, output logic [W-1:0] q);\n"
    "  sub #(.N(W)) u_sub (.clk, .d, .q);\n"
    "  sky130_fd_sc_hd__conb_1 u_tie ();\nendmodule\n"
)
_SUB_BB = (
    "(* blackbox *)\nmodule sub #(parameter int N = 1) "
    "(input logic clk, input logic [N-1:0] d, output logic [N-1:0] q);\nendmodule\n"
)
_CONB_LIB = (
    "library (cells) {\n  cell (sky130_fd_sc_hd__conb_1) {\n    area : 1;\n  }\n}\n"
)


@pytest.mark.skipif(
    _YOSYS is None or not os.environ.get("RTL_BUDDY_SLANG_PLUGIN"),
    reason="yosys or the yosys-slang plugin (RTL_BUDDY_SLANG_PLUGIN) not available",
)
def test_the_slang_probe_ignores_modules_the_tops_body_instances(tmp_path):
    """d4: a block that instances a cell and a sub-block no source defines."""
    record = _probe_sources(
        tmp_path, "slang", {"W": 16}, {"blk.sv": _BLK_WITH_CHILDREN}
    )
    assert parse_value(record.parameters["W"])[0] == 16
    assert parse_value(record.parameters["AW"])[0] == 4


@pytest.mark.skipif(_YOSYS is None, reason="yosys not installed")
def test_the_native_probe_reads_the_synthesis_liberty(tmp_path):
    """d4: the native frontend elaborates the body, so its cells must be known."""
    lib = _write(tmp_path / "cells.lib", _CONB_LIB)
    record = _probe_sources(
        tmp_path,
        "verilog",
        {"W": 16},
        {"sub_bb.sv": _SUB_BB, "blk.sv": _BLK_WITH_CHILDREN},
        libs=[lib],
    )
    assert parse_value(record.parameters["W"])[0] == 16


@pytest.mark.skipif(_YOSYS is None, reason="yosys not installed")
def test_the_native_probe_finds_a_hashed_derived_module(tmp_path):
    """d5: with several overrides Yosys names the derived module `$paramod$<sha1>\\blk`."""
    record = _probe_sources(
        tmp_path,
        "verilog",
        {"W": 16, "K": 5, "INIT": "64'hdeadbeefcafef00d", "DEPTH": 7},
        {
            "blk.v": (
                "module blk #(parameter W = 8, parameter K = 3, parameter [63:0] INIT"
                " = 64'h0, parameter DEPTH = 4) (input clk, input [W-1:0] d, output "
                "reg [W-1:0] q);\n  always @(posedge clk) q <= d ^ INIT[W-1:0] ^ K ^ "
                "DEPTH;\nendmodule\n"
            )
        },
    )
    assert not record.complete
    assert record.order == ["W", "K", "INIT", "DEPTH"]
    assert literals_equal(record.parameters["INIT"], "64'hdeadbeefcafef00d")
    assert parse_value(record.parameters["DEPTH"])[0] == 7


@pytest.mark.skipif(
    _YOSYS is None or not os.environ.get("RTL_BUDDY_SLANG_PLUGIN"),
    reason="yosys or the yosys-slang plugin (RTL_BUDDY_SLANG_PLUGIN) not available",
)
def test_the_slang_probe_records_strings_and_imported_headers(tmp_path):
    """d1: a header after a package import, with string and signed parameters."""
    record = _probe_sources(
        tmp_path,
        "slang",
        {"W": 16, "S": "cd"},
        {
            "pkg.sv": "package p;\n  typedef logic [3:0] n_t;\nendpackage\n",
            "blk.sv": (
                "module blk import p::*; #(parameter int W = 8, parameter bit signed "
                '[7:0] N = -3, parameter string S = "ab") (input logic clk, input '
                "n_t x);\nendmodule\n"
            ),
        },
    )
    assert record.order == ["W", "N", "S"]
    assert record.parameters["S"] == '"cd"'
    assert literals_equal(record.parameters["N"], "-8'sd3")
