# rtl-buddy
#
# Copyright 2024 rtl_buddy contributors
#
"""Design knowledge graph: build, merge, results overlay, coverage join, query.

The config, design and binding tiers are unioned by node id (`merge`), written by
`build` to `artefacts/graph/graph.json`, and read by `query`. The volatile `results` and
`coverage` data live in a separate overlay file. The JSON envelope is documented in
docs/concepts/graph.md.
"""

from .binding import (
    BINDING_TIER,
    PY_NODE_PREFIX,
    PYTHON_MODULE_TYPE,
    SOURCE_FILE_TYPE,
    SRC_NODE_PREFIX,
    BindingStage,
    bind_python,
    scan_python_source,
)
from .build import (
    DESIGN_TIER,
    VIEW_GRAPH_MIN_VERSION,
    FlowRunTarget,
    GraphBuild,
    TestbenchTarget,
    TierReport,
    build_graph,
    flow_runs_from_regressions,
    models_from_design_tree,
    models_from_regression,
    testbenches_from_suites,
)
from .config_tier import (
    CONFIG_TIER,
    DEFAULT_FLOW,
    FLOW_CDC,
    FLOW_FPGA,
    FLOW_FPV,
    FLOW_SIM,
    FLOW_SOURCES,
    FLOW_SYNTH,
    GRAPH_JSON_NAME,
    GRAPH_META_NAME,
    SCHEMA_VERSION,
    ConfigTier,
    build_config_tier,
    default_graph_dir,
    extract_config_tier,
    serialize_graph,
    write_graph_json,
    write_graph_meta,
)
from .coverage import (
    COVERAGE_SCHEMA_VERSION,
    STATUS_DECLARED_ONLY,
    STATUS_EXERCISED,
    STATUS_OBSERVED_UNDECLARED,
    CoverageJoin,
    annotate_coverage,
    coverage_block,
    coverage_for_node,
    join_coverage,
)
from .query import (
    DEFAULT_DEPTH,
    DEFAULT_LIMIT,
    DEFAULT_MAX_PATHS,
    MAX_DEPTH,
    QUERY_SCHEMA_VERSION,
    GraphContext,
    GraphIndex,
    GraphQueryError,
    explain,
    load_context,
    load_graph,
    match_nodes,
)
from .merge import (
    MERGED_TIER,
    TIER_ORDER,
    dangling_targets,
    merge_graphs,
    stitch_points,
)
from .query import (
    neighborhood,
    node_summary,
)
from .query import path as query_path
from .query import query as query_graph
from .query import resolve_node, test_status
from .results import (
    OVERLAY_FILETYPE,
    OVERLAY_SCHEMA_VERSION,
    RESULTS_OVERLAY_NAME,
    ResultsOverlay,
    annotate_graph,
    collect_results,
    load_overlay,
    overlay_for_node,
    refresh_results_overlay,
    results_overlay_path,
    write_overlay,
)

__all__ = [
    "BINDING_TIER",
    "CONFIG_TIER",
    "COVERAGE_SCHEMA_VERSION",
    "DEFAULT_FLOW",
    "DESIGN_TIER",
    "FLOW_CDC",
    "FLOW_FPGA",
    "FLOW_FPV",
    "FLOW_SIM",
    "FLOW_SOURCES",
    "FLOW_SYNTH",
    "GRAPH_JSON_NAME",
    "GRAPH_META_NAME",
    "MERGED_TIER",
    "OVERLAY_FILETYPE",
    "OVERLAY_SCHEMA_VERSION",
    "PY_NODE_PREFIX",
    "SOURCE_FILE_TYPE",
    "SRC_NODE_PREFIX",
    "QUERY_SCHEMA_VERSION",
    "PYTHON_MODULE_TYPE",
    "RESULTS_OVERLAY_NAME",
    "SCHEMA_VERSION",
    "STATUS_DECLARED_ONLY",
    "STATUS_EXERCISED",
    "STATUS_OBSERVED_UNDECLARED",
    "TIER_ORDER",
    "VIEW_GRAPH_MIN_VERSION",
    "DEFAULT_DEPTH",
    "DEFAULT_LIMIT",
    "DEFAULT_MAX_PATHS",
    "MAX_DEPTH",
    "BindingStage",
    "ConfigTier",
    "CoverageJoin",
    "FlowRunTarget",
    "GraphContext",
    "GraphIndex",
    "GraphQueryError",
    "GraphBuild",
    "ResultsOverlay",
    "TestbenchTarget",
    "TierReport",
    "annotate_coverage",
    "annotate_graph",
    "bind_python",
    "build_graph",
    "build_config_tier",
    "collect_results",
    "coverage_block",
    "coverage_for_node",
    "dangling_targets",
    "default_graph_dir",
    "explain",
    "extract_config_tier",
    "flow_runs_from_regressions",
    "join_coverage",
    "load_context",
    "load_graph",
    "load_overlay",
    "match_nodes",
    "merge_graphs",
    "models_from_design_tree",
    "models_from_regression",
    "neighborhood",
    "node_summary",
    "overlay_for_node",
    "query_graph",
    "query_path",
    "refresh_results_overlay",
    "resolve_node",
    "results_overlay_path",
    "scan_python_source",
    "serialize_graph",
    "stitch_points",
    "testbenches_from_suites",
    "test_status",
    "write_graph_json",
    "write_graph_meta",
    "write_overlay",
]
