"""Generate CDC timing exceptions from the rtl-buddy-cdc domain map and reset-domain map JSONs.

Used by ``rb cdc --emit-constraints``. Pure functions with no subprocess or tool dependency.

Per verified crossing:
  * ``set_max_delay -datapath_only`` bounded to the destination clock period,
  * ``set_bus_skew`` as well for multi-bit buses.
At the top level (not when ``scoped``):
  * ``create_clock`` echoed from the analysis SDC and ``set_clock_groups -asynchronous``.
Per reset synchronizer:
  * ``set_false_path`` to the synchronizer's first stage.

SDC and XDC output are identical apart from the header.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class ConstraintEntry:
    """One emitted exception plus why it was emitted (machine manifest row)."""

    kind: str  # max_delay | bus_skew | clock_groups | create_clock | reset_false_path
    target: str  # the instance / clock the exception applies to
    width: int = 1
    rationale: str = ""
    line: str = ""  # the emitted constraint text


@dataclass
class EmitResult:
    text: str  # the full constraint file
    entries: list[ConstraintEntry] = field(default_factory=list)
    # Scoped crossings whose capture instance flattened to the design top (e.g. Yosys
    # `flatten`); the CLI treats a non-empty list as an error.
    unscoped: list[str] = field(default_factory=list)

    @property
    def manifest(self) -> list[dict]:
        return [
            {
                "kind": e.kind,
                "target": e.target,
                "width": e.width,
                "rationale": e.rationale,
            }
            for e in self.entries
        ]


def _strip_top(path: str) -> str:
    """Drop the leading ``<top>.`` and join with ``/``: ``top.u_hs.u_req_sync`` -> ``u_hs/u_req_sync``."""
    parts = path.split(".")
    rel = parts[1:] if len(parts) > 1 else parts
    return "/".join(rel)


def _unscopable(inst: str, top: str) -> bool:
    """True when the instance is empty or flattened to the design top, so no IP-relative selector exists."""
    if not inst:
        return True
    rel = _strip_top(inst)
    return rel == "" or rel == top or inst == top


def _cells(path: str) -> str:
    """A ``get_cells`` selector for the sequential cells under an instance path.

    The path is relative to the design root, or to the IP with ``SCOPED_TO_REF``.
    ``-filter {IS_SEQUENTIAL}`` avoids Vivado 18-401/18-402 invalid endpoint warnings.
    Do not add ``-hierarchical``: Vivado then matches leaf names only, so a pattern
    containing ``/`` binds to nothing.
    """
    return f"[get_cells {_strip_top(path)}/* -filter {{IS_SEQUENTIAL}}]"


def _safe_crossings(domain_map: dict) -> list[dict]:
    """Crossings the SDC declares asynchronous (``async_per_sdc``); others are left to normal timing."""
    out = []
    for c in domain_map.get("crossings", []):
        if c.get("async_per_sdc", True):
            out.append(c)
    return out


def _period_for(domain_map: dict, clock: str) -> float | None:
    for c in domain_map.get("clocks", []):
        if c.get("name") == clock:
            return c.get("period")
    return None


def generate_constraints(
    domain_map: dict,
    reset_map: dict | None = None,
    *,
    fmt: str = "sdc",
    scoped: bool = False,
) -> EmitResult:
    """Build the exception set for ``domain_map`` and ``reset_map``.

    ``fmt`` is ``"sdc"`` or ``"xdc"``. ``scoped`` emits IP-relative cell selectors and
    omits clock definitions and groups, which belong to the instantiating design.
    """
    if fmt not in ("sdc", "xdc"):
        raise ValueError(f"unknown constraint format {fmt!r} (expected sdc or xdc)")
    reset_map = reset_map or {}
    entries: list[ConstraintEntry] = []
    lines: list[str] = []

    top = domain_map.get("design", {}).get("top", "")
    lines.append(f"# CDC timing exceptions for {top or 'design'} ({fmt.upper()})")
    lines.append("# Generated by `rb cdc --emit-constraints` from the verified")
    lines.append("# crossing set — do not hand-edit; regenerate when the RTL changes.")
    if scoped:
        lines.append(
            "# Scoped: cells are IP-relative; apply with SCOPED_TO_REF so every "
            "instantiation inherits these (top clock defs/groups belong to the parent)."
        )
    lines.append("")

    if not scoped:
        for clk in domain_map.get("clocks", []):
            name, period = clk.get("name"), clk.get("period")
            ports = clk.get("ports") or [name]
            if name and period is not None:
                line = (
                    f"create_clock -name {name} -period {period} "
                    f"[get_ports {{{' '.join(ports)}}}]"
                )
                lines.append(line)
                entries.append(
                    ConstraintEntry(
                        kind="create_clock",
                        target=name,
                        rationale=f"{period} ns clock from the analysis SDC",
                        line=line,
                    )
                )
        for grp in domain_map.get("clock_groups", []):
            if grp.get("kind") != "asynchronous":
                continue
            members = grp.get("members", [])
            grp_str = " ".join(f"-group {{{' '.join(m)}}}" for m in members if m)
            line = f"set_clock_groups -asynchronous {grp_str}"
            lines.append(line)
            entries.append(
                ConstraintEntry(
                    kind="clock_groups",
                    target=" / ".join("+".join(m) for m in members),
                    rationale="domains are mutually asynchronous per the analysis",
                    line=line,
                )
            )
        lines.append("")

    unscoped: list[str] = []
    for c in _safe_crossings(domain_map):
        src_inst = c.get("src_source_instance_path", "")
        dst_inst = c.get("dst_source_instance_path", "")
        width = int(c.get("width", 1))
        dst_clk = c.get("dst_clock", "")
        if scoped and _unscopable(dst_inst, top):
            # A `<top>/*` wildcard would over-constrain the IP; emit a marker instead.
            tgt = _strip_top(c.get("dst_flop", "")) or dst_clk
            unscoped.append(tgt)
            lines.append(
                f"# UNSCOPED: {c.get('src_clock', '?')} -> {dst_clk} crossing at "
                f"{tgt} — capture instance flattened to the top; scoped emit needs "
                "a hierarchy-preserving frontend (frontend: slang)"
            )
            continue
        period = _period_for(domain_map, dst_clk)
        if period is None:
            lines.append(
                f"# WARNING: no period for {dst_clk}; max_delay for "
                f"{_strip_top(dst_inst)} omitted (add create_clock to the SDC)"
            )
            continue
        src_clk = c.get("src_clock", "")
        if "." not in src_inst:
            # Source registers sit directly in the top. Flat output uses the launch clock,
            # which avoids non-sequential startpoint warnings; scoped output cannot name it.
            frm = (
                f"[get_clocks {{{src_clk}}}]"
                if (src_clk and not scoped)
                else "[get_cells -hierarchical * -filter {IS_SEQUENTIAL}]"
            )
        else:
            frm = _cells(src_inst)
        to = _cells(dst_inst)
        md = f"set_max_delay -datapath_only {period} -from {frm} -to {to}"
        lines.append(md)
        entries.append(
            ConstraintEntry(
                kind="max_delay",
                target=_strip_top(dst_inst),
                width=width,
                rationale=(
                    f"{dst_clk} crossing bounded to one {dst_clk} period "
                    f"({period} ns); -datapath_only ignores the unrelated launch clock"
                ),
                line=md,
            )
        )
        if width > 1:
            bs = f"set_bus_skew {period} -from {frm} -to {to}"
            lines.append(bs)
            entries.append(
                ConstraintEntry(
                    kind="bus_skew",
                    target=_strip_top(dst_inst),
                    width=width,
                    rationale=(
                        f"{width}-bit bus: bound inter-bit skew to {period} ns so a "
                        "false_path cannot hide bit-to-bit incoherency"
                    ),
                    line=bs,
                )
            )

    reset_syncs = reset_map.get("reset_synchronizers", [])
    seen_reset: set[str] = set()
    if reset_syncs:
        lines.append("")
    for rs in reset_syncs:
        inst = rs.get("instance_path", "")
        async_in = rs.get("async_in", "")
        # The map lists one entry per flop; emit one exception per instance.
        inst_key = inst.rsplit(".", 1)[0] if "." in inst else inst
        if inst_key in seen_reset:
            continue
        seen_reset.add(inst_key)
        to = _cells(inst_key)
        fp = f"set_false_path -to {to}"
        lines.append(fp)
        entries.append(
            ConstraintEntry(
                kind="reset_false_path",
                target=_strip_top(inst_key),
                rationale=(
                    f"reset synchronizer (async-assert from {async_in}, "
                    "sync-deassert): the async path is exempt from data-path timing"
                ),
                line=fp,
            )
        )

    lines.append("")
    return EmitResult(text="\n".join(lines), entries=entries, unscoped=unscoped)
