#!/usr/bin/env python3
"""Build dev and every published major with Docusaurus."""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import tarfile
from pathlib import Path


REPO_ROOT = Path(__file__).parent.parent


def _run(*args: str) -> str:
    result = subprocess.run(
        args,
        cwd=REPO_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def latest_stable_tag(major: str) -> str:
    tags = _run("git", "tag", "--list", f"{major}.*.*", "--sort=-v:refname")
    stable = [
        tag
        for tag in tags.splitlines()
        if re.fullmatch(rf"{re.escape(major)}\.[0-9]+\.[0-9]+", tag)
    ]
    if not stable:
        raise RuntimeError(f"no stable tag found for {major}")
    return stable[0]


def _extract_docs(tag: str, destination: Path) -> Path:
    destination.mkdir(parents=True)
    archive = destination / "docs.tar"
    with archive.open("wb") as stream:
        subprocess.run(
            ["git", "archive", "--format=tar", tag, "docs"],
            cwd=REPO_ROOT,
            check=True,
            stdout=stream,
        )
    with tarfile.open(archive) as source:
        source.extractall(destination, filter="data")
    return destination / "docs"


def build_version(
    version: str,
    *,
    docs_dir: Path,
    edit_ref: str,
    output: Path,
    versions: list[str],
    autogenerated_sidebar: bool,
) -> None:
    env = os.environ.copy()
    env.update(
        {
            "DOCS_PATH": str(docs_dir),
            "DOCS_BASE_URL": f"/rtl_buddy/{version}/",
            "DOCS_ROOT_BASE_URL": "/rtl_buddy/",
            "DOCS_VERSION": version,
            "DOCS_VERSIONS": ",".join(versions),
            "DOCS_EDIT_REF": edit_ref,
            "DOCS_AUTOGENERATED_SIDEBAR": str(autogenerated_sidebar).lower(),
        }
    )
    shutil.rmtree(REPO_ROOT / ".docusaurus", ignore_errors=True)
    subprocess.run(["npm", "run", "build"], cwd=REPO_ROOT, env=env, check=True)
    target = output / version
    if target.exists():
        shutil.rmtree(target)
    shutil.move(REPO_ROOT / "build", target)


def build_all(output: Path, versions: list[str]) -> None:
    output = output.resolve()
    if output.exists():
        shutil.rmtree(output)
    output.mkdir(parents=True)

    temp_path = REPO_ROOT / ".docusaurus-historical-docs"
    shutil.rmtree(temp_path, ignore_errors=True)
    temp_path.mkdir()
    try:
        for version in versions:
            if version == "dev":
                docs_dir = REPO_ROOT / "docs"
                edit_ref = "main"
                autogenerated = False
            else:
                edit_ref = latest_stable_tag(version)
                docs_dir = _extract_docs(edit_ref, temp_path / version)
                autogenerated = True
            print(f"Building {version} from {edit_ref}", flush=True)
            build_version(
                version,
                docs_dir=docs_dir,
                edit_ref=edit_ref,
                output=output,
                versions=versions,
                autogenerated_sidebar=autogenerated,
            )
    finally:
        shutil.rmtree(temp_path, ignore_errors=True)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=REPO_ROOT / "builds")
    parser.add_argument(
        "--versions",
        default=os.environ.get("DOCS_VERSIONS", "dev,v6,v5,v4,v3,v2"),
    )
    args = parser.parse_args()
    versions = [item.strip() for item in args.versions.split(",") if item.strip()]
    build_all(args.output, versions)


if __name__ == "__main__":
    main()
